let quizzes = [
    {
        "_id": "Q101",
        "title": "Rocket Propulsion Fundamentals",
        "course": "RS101",
        "description": "Test your knowledge of basic rocket propulsion concepts",
        "quizType": "Graded Quiz",
        "points": 100,
        "assignmentGroup": "Quizzes",
        "shuffleAnswers": true,
        "timeLimit": 20,
        "multipleAttempts": false,
        "showCorrectAnswers": "after_submission",
        "accessCode": "",
        "oneQuestionAtATime": true,
        "webcamRequired": false,
        "lockQuestionsAfterAnswering": false,
        "due_date": "2024-05-13",
        "available_date": "2024-05-06",
        "until_date": "2024-05-13"
    },
    {
        "_id": "Q102",
        "title": "Combustion Processes Survey",
        "course": "RS101",
        "description": "Please provide feedback on the combustion processes module",
        "quizType": "Graded Survey",
        "points": 50,
        "assignmentGroup": "Assignments",
        "shuffleAnswers": false,
        "timeLimit": 30,
        "multipleAttempts": true,
        "showCorrectAnswers": "never",
        "accessCode": "COMB2024",
        "oneQuestionAtATime": false,
        "webcamRequired": false,
        "lockQuestionsAfterAnswering": false,
        "due_date": "2024-05-14",
        "available_date": "2024-05-07",
        "until_date": "2024-05-14",
        "allowedAttempts": 3
    },
    {
        "_id": "Q201",
        "title": "Aerodynamics Practice",
        "course": "RS102",
        "description": "Practice quiz for aerodynamics principles",
        "quizType": "Practice Quiz",
        "points": 0,
        "assignmentGroup": "Quizzes",
        "shuffleAnswers": true,
        "timeLimit": 0,
        "multipleAttempts": true,
        "showCorrectAnswers": "always",
        "accessCode": "",
        "oneQuestionAtATime": true,
        "webcamRequired": false,
        "lockQuestionsAfterAnswering": false,
        "due_date": "2024-05-16",
        "available_date": "2024-05-09",
        "until_date": "2024-05-16",
        "allowedAttempts": 999
    }
];

export default quizzes;
